### PR TITLE
Support OpenID Connect tokens

### PR DESCRIPTION
**Pull request by cdevienne**
OpenID Connect is based on OAuth but returns a special token (a jwt) instead of a regular oauth token.
This PR add a basic support for receiving such a token.

### CODE REVIEW

**Comment by KtorZ** [comment]
Hi! 

Thanks for reaching out through a PR. However, I am afraid not to want to merge this in. OpenID Connect is actually a different protocol, even though it heavily relies on OAuth 2.0. 

This library provides the necessary components to handle OAuth 2.0 delegation mechanism but OpenID Connect (or any other protocol builds on top of it) is out of scope here.

I invite you however to create an OpenID Connect library and to leverage this library to implement the Implicit Flow for OpenID Connect.

**Comment by cdevienne** [comment]
Hi

No problem, I kind of expected such a reply but wanted to make sure before doing a new library.

Cheers

**Comment by cdevienne** [comment]
Could I just add a 'Custom' ResponseType ? It would allow me to use the OAuth.Implicit.authorize function and only have to deal with the parsing of the response.

**Comment by KtorZ** [comment]
There might be room for something indeed. See #6

**Pull request closed without merging**
