### PR TITLE
Upgrade http library

### PR DESCRIPTION
**Pull request by michaelwebb76**
* Upgrade http -> 2.0.0
* Use default formatting for `elm.json` file
* All passes `elm make` for library and examples

### CODE REVIEW

**Comment by michaelwebb76** [comment]
Resolves https://github.com/truqu/elm-oauth2/issues/15

**Comment by KtorZ** [comment]
Sorry it's taking a bit of time, I've been dragged into other business ATM. I've started integrating the work and will likely finalize that somewhere this week :+1:

**Comment by KtorZ** [comment]
Merged in 333d6ea289933824237640480dd5c05a9e7e9c47

Note that I inverted the order of arguments for `makeTokenRequest`. Sorry for the time it took I am not having the free time I'd like to have :disappointed: 

Thanks for the PR and feedback :heart:

**Comment by michaelwebb76** [comment]
Thanks so much @KtorZ, very much appreciated

**Pull request closed without merging**
